version: '3'

services:
  filebeat:
    image: elastic/filebeat:6.4.2
    container_name: filebeat
    user: "0:0"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/log/justitia/justitia.log:/var/log/justitia/justitia.log:ro"
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "./justitia-logs.yml:/usr/share/filebeat/prospectors.d/justitia-logs.yml"
  metricbeat:
    image: elastic/metricbeat:6.4.2
    container_name: metricbeat
    user: "0:0"
    privileged: true
    network_mode: "host"
    volumes:
      - "/proc:/hostfs/proc:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/:/hostfs:ro"
      - "./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml"
      - "./justitia-metrics.yml:/usr/share/metricbeat/modules.d/justitia-metrics.yml"
      - "./golang.yml:/usr/share/metricbeat/modules.d/golang.yml"
    command: "-system.hostfs=/hostfs"
