filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.template:
  name: "justitia-logs-*"
  pattern: "justitia-logs-*"


processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
  index: "justitia-logs-%{+yyyy.MM.dd}"
