################################################################################
#
#   NODE PROPERTIES
#
#   - List all algorithm and policy specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:

    # Operational algorithm: "SHA256", "Keccak512", "Keccak256", "SM3"
    hashAlgorithm: SHA256

    # Api gateway for api
    apigateway: tcp://0.0.0.0:47768

    # Node info, specified node information
    node:
        address: 333c3310824b7c685133f2bedb2ca4b8b4df633d

    # Block chain setting
    # Operational plugin: "memorydb" or "leveldb"
    blockchain:
        plugin: memorydb
        statepath: ./../state
        datapath: ./../block

    # Tx pool setting
    txpool:
        globalslots: 4096
        txsPerBlock: 512

    # Role setting
    role:
        policy: solo

    # Participates setting
    participates:
        policy: solo
        participates: 4

    # Consensus setting
    consensus:
        policy: solo

    # Block produce interval for solo mode
    soloModeBlockProducedInterval: 2

################################################################################
#
#   SECTION: monitor
#
#   - This section define monitor setting
#
################################################################################
monitor:

    # The prometheus setting
    prometheus:
        enabled: true
        port: 47780
        maxOpenConnections: 3

    expvar:
        enabled: true
        port: 6060
        path: /debug/vars
